language: python

python:
 - "3.6"

install:
  - pip install pipenv
  - pipenv install -d

script:
  - pytest --cov=./ --cov-report xml

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
