version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:11.1
      - image: redis

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile" }}

      - run:
          name: run tests
          command: |
            pipenv run pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
